// generated 2004/7/24 17:45:26 BST by fabrice@amra.dyndns.org.(none)
// using glademm V2.6.0_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/fabrice/Projects/MetaSE/metase/UI/GTK2/metase-gtk2.glade
// for gtk 2.4.0 and gtkmm 2.2.12
//
// Please modify the corresponding derived classes in ./src/aboutDialog.hh and./src/aboutDialog.cc

#ifndef _ABOUTDIALOG_GLADE_HH
#  define _ABOUTDIALOG_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/dialog.h>
#include <gtkmm/button.h>
#include <gtkmm/label.h>

class aboutDialog_glade : public Gtk::Dialog
{  
        
        GlademmData *gmm_data;
public:
        class Gtk::Dialog * aboutDialog;
protected:
        class Gtk::Button * closebutton1;
        class Gtk::Label * nameLabel;
        
        aboutDialog_glade();
        
        ~aboutDialog_glade();
};
#endif
