// generated 2007/1/11 20:22:49 SGT by fabrice@amra.dyndns.org.(none)
// using glademm V2.12.1
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/fabrice/Projects/MetaSE/pinot/UI/GTK2/metase-gtk2.glade
// for gtk 2.10.4 and gtkmm 2.10.5
//
// Please modify the corresponding derived classes in ./src/dateDialog.cc


#if defined __GNUC__ && __GNUC__ < 3
#error This program will crash if compiled with g++ 2.x
// see the dynamic_cast bug in the gtkmm FAQ
#endif //
#include "config.h"
/*
 * Standard gettext macros.
 */
#ifdef ENABLE_NLS
#  include <libintl.h>
#  undef _
#  define _(String) dgettext (GETTEXT_PACKAGE, String)
#  ifdef gettext_noop
#    define N_(String) gettext_noop (String)
#  else
#    define N_(String) (String)
#  endif
#endif
#include <gtkmmconfig.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#include <sigc++/compatibility.h>
#include <sigc++/bind.h>
#define GMM_GTKMM_22_24(a,b) b
#else //gtkmm 2.2
#define GMM_GTKMM_22_24(a,b) a
#endif //
#include "dateDialog_glade.hh"
#include <gdk/gdkkeysyms.h>
#include <gtkmm/accelgroup.h>
#include <gtkmm/button.h>
#include <gtkmm/buttonbox.h>
#include <gtkmm/box.h>
#ifndef ENABLE_NLS
#  define textdomain(String) (String)
#  define gettext(String) (String)
#  define dgettext(Domain,Message) (Message)
#  define dcgettext(Domain,Message,Type) (Message)
#  define bindtextdomain(Domain,Directory) (Domain)
#  define _(String) (String)
#  define N_(String) (String)
#endif


dateDialog_glade::dateDialog_glade(
)
{  
   
   Gtk::Dialog *dateDialog = this;
   gmm_data = new GlademmData(get_accel_group());
   
   Gtk::Button *cancelbutton4 = Gtk::manage(new class Gtk::Button(Gtk::StockID("gtk-cancel")));
   Gtk::Button *okbutton2 = Gtk::manage(new class Gtk::Button(Gtk::StockID("gtk-ok")));
   dateCalendar = Gtk::manage(new class Gtk::Calendar());
   cancelbutton4->set_flags(Gtk::CAN_FOCUS);
   cancelbutton4->set_flags(Gtk::CAN_DEFAULT);
   cancelbutton4->set_relief(Gtk::RELIEF_NORMAL);
   okbutton2->set_flags(Gtk::CAN_FOCUS);
   okbutton2->set_flags(Gtk::CAN_DEFAULT);
   okbutton2->set_relief(Gtk::RELIEF_NORMAL);
   dateDialog->get_action_area()->property_layout_style().set_value(Gtk::BUTTONBOX_END);
   dateCalendar->set_flags(Gtk::CAN_FOCUS);
   dateCalendar->display_options(Gtk::CALENDAR_SHOW_HEADING|Gtk::CALENDAR_SHOW_DAY_NAMES);
   dateDialog->get_vbox()->set_homogeneous(false);
   dateDialog->get_vbox()->set_spacing(0);
   dateDialog->get_vbox()->pack_start(*dateCalendar);
   dateDialog->set_title(_("Date"));
   dateDialog->set_modal(false);
   dateDialog->property_window_position().set_value(Gtk::WIN_POS_NONE);
   dateDialog->set_resizable(true);
   dateDialog->property_destroy_with_parent().set_value(false);
   dateDialog->set_has_separator(true);
   dateDialog->add_action_widget(*cancelbutton4, -6);
   dateDialog->add_action_widget(*okbutton2, -5);
   cancelbutton4->show();
   okbutton2->show();
   dateCalendar->show();
   dateDialog->show();
}

dateDialog_glade::~dateDialog_glade()
{  delete gmm_data;
}
