// generated 2005/11/6 16:25:47 SGT by fabrice@amra.dyndns.org.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/fabrice/Projects/MetaSE/metase/UI/GTK2/metase-gtk2.glade
// for gtk 2.6.10 and gtkmm 2.6.2
//
// Please modify the corresponding derived classes in ./src/importDialog.hh and./src/importDialog.cc

#ifndef _IMPORTDIALOG_GLADE_HH
#  define _IMPORTDIALOG_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/dialog.h>
#include <gtkmm/button.h>
#include <gtkmm/entry.h>
#include <gtkmm/label.h>
#include <gtkmm/spinbutton.h>
#include <gtkmm/combobox.h>
#include <gtkmm/table.h>

class importDialog_glade : public Gtk::Dialog
{  
        
        GlademmData *gmm_data;
public:
        class Gtk::Dialog * importDialog;
protected:
        class Gtk::Button * importOkButton;
        class Gtk::Button * selectButton;
        class Gtk::Entry * locationEntry;
        class Gtk::Entry * titleEntry;
        class Gtk::Label * titleLabel;
        class Gtk::Label * depthLabel;
        class Gtk::SpinButton * depthSpinbutton;
        class Gtk::ComboBox * typeCombobox;
        class Gtk::Table * docTable;
        
        importDialog_glade();
        
        ~importDialog_glade();
private:
        virtual void on_importOkButton_clicked() = 0;
        virtual void on_selectButton_clicked() = 0;
        virtual void on_locationEntry_changed() = 0;
        virtual void on_typeCombobox_changed() = 0;
};
#endif
