// generated 2006/11/1 20:52:15 SGT by fabrice@amra.dyndns.org.(none)
// using glademm V2.12.1
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/fabrice/Projects/MetaSE/pinot/UI/GTK2/metase-gtk2.glade
// for gtk 2.10.4 and gtkmm 2.10.2
//
// Please modify the corresponding derived classes in ./src/prefsDialog.hh and./src/prefsDialog.cc

#ifndef _PREFSDIALOG_GLADE_HH
#  define _PREFSDIALOG_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/dialog.h>
#include <gtkmm/button.h>
#include <gtkmm/label.h>
#include <gtkmm/entry.h>
#include <gtkmm/checkbutton.h>
#include <gtkmm/colorbutton.h>
#include <gtkmm/treeview.h>
#include <gtkmm/notebook.h>

class prefsDialog_glade : public Gtk::Dialog
{  
        
        GlademmData *gmm_data;
public:
        class Gtk::Dialog * prefsDialog;
protected:
        class Gtk::Button * prefsCancelbutton;
        class Gtk::Button * prefsOkbutton;
        class Gtk::Label * apiKeyLabel;
        class Gtk::Entry * apiKeyEntry;
        class Gtk::CheckButton * ignoreRobotsCheckbutton;
        class Gtk::CheckButton * enableCompletionCheckbutton;
        class Gtk::ColorButton * newResultsColorbutton;
        class Gtk::TreeView * labelsTreeview;
        class Gtk::Button * addLabelButton;
        class Gtk::Button * removeLabelButton;
        class Gtk::TreeView * directoriesTreeview;
        class Gtk::Button * addDirectoryButton;
        class Gtk::Button * removeDirectoryButton;
        class Gtk::TreeView * mailTreeview;
        class Gtk::Button * addAccountButton;
        class Gtk::Button * removeAccountButton;
        class Gtk::TreeView * patternsTreeview;
        class Gtk::Button * addPatternButton;
        class Gtk::Button * removePatternButton;
        class Gtk::Notebook * prefsNotebook;
        
        prefsDialog_glade();
        
        ~prefsDialog_glade();
private:
        virtual void on_prefsOkbutton_clicked() = 0;
        virtual void on_addLabelButton_clicked() = 0;
        virtual void on_removeLabelButton_clicked() = 0;
        virtual void on_addDirectoryButton_clicked() = 0;
        virtual void on_removeDirectoryButton_clicked() = 0;
        virtual void on_addAccountButton_clicked() = 0;
        virtual void on_removeAccountButton_clicked() = 0;
        virtual void on_addPatternButton_clicked() = 0;
        virtual void on_removePatternButton_clicked() = 0;
};
#endif
