// generated 2006/3/7 21:04:59 SGT by fabrice@amra.dyndns.org.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/fabrice/Projects/MetaSE/pinot/UI/GTK2/metase-gtk2.glade
// for gtk 2.6.10 and gtkmm 2.6.2
//
// Please modify the corresponding derived classes in ./src/prefsDialog.hh and./src/prefsDialog.cc

#ifndef _PREFSDIALOG_GLADE_HH
#  define _PREFSDIALOG_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/dialog.h>
#include <gtkmm/button.h>
#include <gtkmm/label.h>
#include <gtkmm/entry.h>
#include <gtkmm/combobox.h>
#include <gtkmm/checkbutton.h>
#include <gtkmm/treeview.h>
#include <gtkmm/notebook.h>

class prefsDialog_glade : public Gtk::Dialog
{  
        
        GlademmData *gmm_data;
public:
        class Gtk::Dialog * prefsDialog;
protected:
        class Gtk::Button * prefsCancelbutton;
        class Gtk::Button * prefsOkbutton;
        class Gtk::Label * apiKeyLabel;
        class Gtk::Entry * apiKeyEntry;
        class Gtk::ComboBox * viewCombobox;
        class Gtk::CheckButton * ignoreRobotsCheckbutton;
        class Gtk::Entry * browserEntry;
        class Gtk::Button * browserButton;
        class Gtk::TreeView * labelsTreeview;
        class Gtk::Button * addLabelButton;
        class Gtk::Button * removeLabelButton;
        class Gtk::TreeView * mailTreeview;
        class Gtk::Button * addAccountButton;
        class Gtk::Button * editAccountButton;
        class Gtk::Button * removeAccountButton;
        class Gtk::Notebook * prefsNotebook;
        
        prefsDialog_glade();
        
        ~prefsDialog_glade();
private:
        virtual void on_prefsOkbutton_clicked() = 0;
        virtual void on_viewCombobox_changed() = 0;
        virtual void on_browserButton_clicked() = 0;
        virtual void on_addLabelButton_clicked() = 0;
        virtual void on_removeLabelButton_clicked() = 0;
        virtual bool on_mailTreeview_button_press_event(GdkEventButton *ev) = 0;
        virtual void on_addAccountButton_clicked() = 0;
        virtual void on_editAccountButton_clicked() = 0;
        virtual void on_removeAccountButton_clicked() = 0;
};
#endif
